[package]
name = "resumes"
version = "0.1.0"
edition = "2024"

[dependencies]
json-resume = { git = "https://github.com/jsonresume/rust-json-resume.git", version = "0.1.0" }
serde_json = "1.0"
bon = "3.6"
chrono = "0.4"
anyhow = "1.0"
