name: Generate resume

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
      - name: Install dependencies
        run: npm install
      - name: Generate artifact
        run: npx tsx ${{ github.workspace }}/render.ts --tex
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ github.workspace }}/artifacts/main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndrewLeung_Resume.pdf
          path: ./artifacts/AndrewLeung_Resume.pdf
